## Packages needed to run sunapee_LER_projections
install.packages("remotes")
remotes::install_github("GLEON/rLakeAnalyzer")
remotes::install_github("aemon-j/GLM3r", ref = "v3.1.1")
remotes::install_github("USGS-R/glmtools", ref = "ggplot_overhaul")
remotes::install_github("aemon-j/FLakeR", ref = "inflow")
remotes::install_github("aemon-j/GOTMr")
remotes::install_github("aemon-j/gotmtools")
remotes::install_github("aemon-j/SimstratR")
remotes::install_github("aemon-j/MyLakeR") 
remotes::install_github("tadhg-moore/LakeEnsemblR", ref = "sunp-isimip")
install.packages("ggplot2")
install.packages("ggpubr")
install.packages("dplyr") 
install.packages("rLakeAnalyzer")
install.packages("reshape")
install.packages("reshape2")
install.packages("RColorBrewer")
install.packages("lubridate")
install.packages("Metrics")
install.packages("plotrix")
install.packages("here")
